spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev
  application:
    name: CloudParentProject-config-dev
---
spring:
  profiles: test
  application:
    name: CloudParentProject-config-test